CREATE TABLE ROLES (
	ID int NOT NULL AUTO_INCREMENT,
    ROLE varchar(255) DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USERS (
	ID int NOT NULL AUTO_INCREMENT,
    FIRST_NAME varchar(50) NOT NULL,
    LAST_NAME varchar(50) NOT NULL,
    EMAIL varchar(50) NOT NULL,
    PASSWORD varchar(500) NOT NULL,
    STATUS varchar(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLE_MAPPING (
	USER_ID int NOT NULL,
    ROLE_ID int NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    KEY IDX_ROLE_ID (ROLE_ID),
    CONSTRAINT AUTH_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT AUTH_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID)
);